version: '3.8'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # OpenWire
      - "5672:5672" # AMQP
      - "1883:1883" # MQTT
      - "61613:61613" # STOMP
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
    volumes:
      - activemq_data:/data/activemq
      - activemq_log:/var/log/activemq

volumes:
  activemq_data:
  activemq_log:
